### ISSUE TITLE
Logstash s2i build - Unrecoverable plugin error

### ISSUE THREAD

**Issue by harishkb27** [TheRemoteLab/elk-openshift3#1]
@bhalothia 
`{:timestamp=>"2016-11-06T02:40:07.978000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Redis host=>\"redis\", type=>\"redis-input\", data_type=>\"list\", key=>\"logstash\", codec=><LogStash::Codecs::JSON charset=>\"UTF-8\">, threads=>1, name=>\"default\", port=>6379, db=>0, timeout=>5, batch_count=>125>\n  Error: initialize: name or service not known", :level=>:error}`

Reproduce:
```sh
make
s2i build test/test-app logstash-builder logstash1
docker run --rm logstash1
```

**Comment by bhalothia** [comment]
@harishkb27 checking it now.

**Comment by bhalothia** [comment]
Installed the logstash-redis-input plugin but still getting authentication error while communication with Redis.

I tried creating a new DeployConfig for Redis with -e REDIS_PASSWORD. However, it's failing to startup.

**Comment by bhalothia** [comment]
`sed: couldn't open temporary file /opt/app-root/src/sedISmNjD: Permission denied
`
